### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by akane-5** [akane-5/entsumugi#117]
## 各種情報
**えんつむぎ**
[サービスURL](https://entsumugi-16d01808acf3.herokuapp.com/)

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- 検索機能
   - [x] 都道府県検索
   - [ ] カテゴリ検索
   - [x] フリーワード検索
   - [x] 地図検索
- [ ] 人気の御朱印一覧
- [ ] アプリの使い方
- [ ] ユーザー登録機能
- [ ]  ログイン機能
- [ ]  ログアウト機能
- [ ] マイページ
- [ ]  Xシェア機能
- [ ]  デジタル御朱印帳

チェックが入っている機能は実装済みです。
未チェックの機能は本リリースにて実装予定となります。

## READMEレビュー時から変更した機能

下記の機能については、READMEレビュー後のスケジュール面談にて相談の上、本リリースに回すことと致しました。
- カテゴリ検索
- 人気の御朱印一覧
- アプリの使い方
- ユーザー登録機能
- ログイン機能
- ログアウト機能
- マイページ
- Xシェア機能
- デジタル御朱印帳

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます！
LGTMです！
本リリースに向けて頑張ってください💪

**Comment by akane-5** [comment]
柏木講師、ご確認いただきありがとうございました！
LGTMありがとうございます！
本リリースに向けてがんばります！

**Comment by akane-5** [comment]
柏木講師、ご確認いただきありがとうございました！
本リリースにむけてがんばります！
