### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by akane-5** [akane-5/entsumugi#4]
### 概要
"Issueベース開発"に基づきissueを作成いたしましたので、レビューをお願いいたします。
GitHubProject：https://github.com/users/akane-5/projects/1/views/1

### 実装予定の機能
- [ ] 都道府県検索
- [ ] カテゴリ検索
- [ ] フリーワード検索
- [ ] 地図検索
- [ ] 人気の御朱印一覧
- [ ] アプリの使い方(ユーザー登録すると使える機能の紹介)
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] パスワードリセット機能
- [ ] メール認証機能
- [ ] Xシェア機能
- [ ] デジタル御朱印帳
- [ ] ブックマーク機能
- [ ] バッジ機能
- [ ] レベル機能
- [ ] お問い合わせフォーム
- [ ] 利用規約
- [ ] プライバシーポリシー

### 必要なページ
- [ ] トップページ(ログイン前)
- [ ] トップページ(ログイン後)
- [ ] 検索ページ
- [ ] 検索結果一覧ページ
- [ ] 人気の御朱印一覧ページ
- [ ] マイページ
- [ ] デジタル御朱印帳作成画面
- [ ] デジタル御朱印帳ページ
- [ ] ブックマーク一覧ページ
- [ ] バッジ一覧ページ
- [ ] アカウント情報ページ
- [ ] アカウント情報編集画面
- [ ] Xシェア画面
- [ ] ユーザー登録ページ
- [ ] ログインページ
- [ ] お問い合わせページ
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by shota-hope** [comment]
提出ありがとうございます。
気になった点をコメントさせていただきます。

以下あたりのストーリーポイント3, 5をもう少し分割した方が良いと思いました。
https://github.com/users/akane-5/projects/1/views/1?pane=issue&itemId=69249169
https://github.com/users/akane-5/projects/1/views/1?pane=issue&itemId=69249172
https://github.com/users/akane-5/projects/1/views/1?pane=issue&itemId=69249238

ご確認よろしくお願いします。

**Comment by akane-5** [comment]
お忙しい中ご確認いただきありがとうございました。

コメントいただきました３件と、関連して１件のissueにつきまして、上から順に以下のように修正しました。

- 28 神社データの取得：ストーリーポイント5
　→追加調査を行い、実装のイメージを高められたのでストーリーポイントを3に変更しました。
　　また実現したいことに対して実装の方向性に誤りがあったため、issueの内容も修正しました。
　　#28 ：ストーリーポイント3

- 29 検索機能の実装：ストーリーポイント5
　→各検索項目ごとに分解しました。
　　#29 ：ストーリーポイント3
　　#56 ：ストーリーポイント3
　　#57 ：ストーリーポイント3
　　
　　また検索機能の実装に関連して、下記のissueも分解しました。
　　27 検索画面に地図表示：ストーリーポイント5
　　→#55 ：ストーリーポイント3
　　　#27 ：ストーリーポイント3
　　　#58 ：ストーリーポイント3

- 37 人気の御朱印一覧の実装：ストーリーポイント5
　→各カテゴリごとに分解しました。
　　#37 ：ストーリーポイント3
　　#59 ：ストーリーポイント3
　　#60 ：ストーリーポイント3

  <br>
分かりづらくなり申し訳ありませんが、ご確認のほどよろしくお願いいたします。

**Comment by ippei-shimizu** [comment]
修正をしていただきありがとうございます。
分解していただいたissueについてはその粒度で良いかと思います。
以下、気になった点をコメントさせていただきます。

--- 

調査と実装のタスクが同じissueで作成されてしまっているように見受けられましたので、調査系のissueと実装系のissueを別々に作成するとストーリーポイントを下げることができると思いました。

https://github.com/akane-5/entsumugi/issues/5
https://github.com/akane-5/entsumugi/issues/8
https://github.com/akane-5/entsumugi/issues/15
https://github.com/akane-5/entsumugi/issues/20
https://github.com/akane-5/entsumugi/issues/44
https://github.com/akane-5/entsumugi/issues/45

**Comment by akane-5** [comment]
お忙しい中ご確認いただきありがとうございました。

コメントいただきました件について下記のように修正しました。
- 該当のissueのストーリーポイントをすべて3に変更
- 該当のissueの調査用のissueを作成(調査にかかるストーリーポイントは2)

<追加で作成した調査のissue>
#61 
#62 
#63 
#64 
#65 
#66 

GitHubProject：https://github.com/users/akane-5/projects/1/views/1

<br>
ご確認のほどよろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
修正いただきありがとうございました。

機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by akane-5** [comment]
ご確認いただきありがとうございました！
